@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 12,
    "backwardDepth": 12,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": false,
    "hideInterfaceCalls": false, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.example.crispycrumbs.view.VideoPlayerFragment",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1322970774 { 
   	label=example
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1709816830 { 
   	label=crispycrumbs
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   CommentActionListener877673192[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)CommentActionListener</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ onDeleteComment(position: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onEditComment(position: int)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];

CommentItem52669585[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CommentItem</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   avatarResId: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   comment: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   date: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   userId: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   userName: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ describeContents(): int</TD></TR>
<TR><TD ALIGN="LEFT" >+ writeToParcel(dest: Parcel, flags: int)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

CommentItemTypeConverter209323434[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CommentItemTypeConverter</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ fromCommentList(list: ArrayList&lt;CommentItem&gt;): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ toCommentList(json: String): ArrayList&lt;CommentItem&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

CommentSection_Adapter1564424876[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)CommentSection_Adapter</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   commentActionListener: CommentActionListener [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   commentItemArrayList: ArrayList&lt;CommentItem&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   context: Context [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   currentUserId: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- formatDateString(originalDate: String): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ onBindViewHolder(holder: MyViewHolder, position: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onCreateViewHolder(parent: ViewGroup, viewType: int): MyViewHolder</TD></TR>
<TR><TD ALIGN="LEFT" >+ removeComment(position: int)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

DateConverter209323434[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)DateConverter</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ dateToTimestamp(date: Date): Long</TD></TR>
<TR><TD ALIGN="LEFT" >+ fromTimestamp(value: Long): Date</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

LoginCallback1199007548[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)LoginCallback</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ onFailure(t: Throwable, statusCode: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onSuccess(loginResponse: LoginResponse)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];

PreviewVideoCard52669585[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)PreviewVideoCard</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   category: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   comments: ArrayList&lt;CommentItem&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   description: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   dislikedBy: ArrayList&lt;String&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   dislikes: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   likedBy: ArrayList&lt;String&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   likes: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   tags: ArrayList&lt;String&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   thumbnail: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   title: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   uploadDate: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   userId: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   videoFile: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   videoId: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   views: int [1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ServerAPI1808078836[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ServerAPI</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   IP: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   retrofit: Retrofit [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   serverAPInterface: ServerAPInterface [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >- buildRetrofit()</TD></TR>
<TR><TD ALIGN="LEFT" >+ constructUrl(path: String): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ getAllVideos(callback: Callback&lt;VideoResponse&gt;)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getCommentsForVideo(videoId: String, callback: Callback&lt;List&lt;CommentItem&gt;&gt;)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getVideoById(videoId: String, callback: Callback&lt;VideoResponse&gt;)</TD></TR>
<TR><TD ALIGN="LEFT" >+ login(userName: String, password: String, rememberMe: boolean, callback: LoginCallback)</TD></TR>
<TR><TD ALIGN="LEFT" >+ postComment(videoId: String, comment: CommentItem, callback: Callback&lt;CommentItem&gt;)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ServerAPInterface1808078836[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)ServerAPInterface</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ dislikeVideo(token: String, request: LikeDislikeRequest): Call&lt;PreviewVideoCard&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getAllVideos(): Call&lt;VideoResponse&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getCommentsForVideo(videoId: String): Call&lt;List&lt;CommentItem&gt;&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getUser(id: String): Call&lt;UserResponse&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getVideoById(videoId: String): Call&lt;VideoResponse&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getVideosByUser(userId: String): Call&lt;List&lt;PreviewVideoCard&gt;&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ incrementVideoViews(videoIdRequest: VideoIdRequest): Call&lt;ApiResponse&lt;Void&gt;&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ likeVideo(token: String, request: LikeDislikeRequest): Call&lt;PreviewVideoCard&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ login(loginRequest: LoginRequest): Call&lt;LoginResponse&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ postComment(videoId: String, comment: CommentItem): Call&lt;CommentItem&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];

SetTypeConverter209323434[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)SetTypeConverter</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ fromSet(set: Set&lt;String&gt;): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ toSet(json: String): Set&lt;String&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

StringListTypeConverter209323434[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)StringListTypeConverter</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ fromArrayList(list: ArrayList&lt;String&gt;): String</TD></TR>
<TR><TD ALIGN="LEFT" >+ toArrayList(json: String): ArrayList&lt;String&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

UserDao668488047[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)UserDao</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getAllUsers(): LiveData&lt;List&lt;UserItem&gt;&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getUserById(userId: String): LiveData&lt;UserItem&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getUserByIdSync(userId: String): UserItem</TD></TR>
<TR><TD ALIGN="LEFT" >+ insertUser(user: UserItem)</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateUser(user: UserItem)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];

UserDao_Impl668488047[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)UserDao_Impl</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   __db: RoomDatabase [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   __insertionAdapterOfUserItem: EntityInsertionAdapter&lt;UserItem&gt; [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   __setTypeConverter: SetTypeConverter [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   __updateAdapterOfUserItem: EntityDeletionOrUpdateAdapter&lt;UserItem&gt; [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getUserById(userId: String): LiveData&lt;UserItem&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getUserByIdSync(userId: String): UserItem</TD></TR>
<TR><TD ALIGN="LEFT" >+ insertUser(user: UserItem)</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateUser(user: UserItem)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

UserItem52669585[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)UserItem</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   country: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   dateOfBirth: Date [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   dislikedVideoIds: Set&lt;String&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   displayedName: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   email: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   followerIds: Set&lt;String&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   followingIds: Set&lt;String&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   likedVideoIds: Set&lt;String&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   password: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   phoneNumber: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   profilePhoto: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   userId: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   userName: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   videosIds: Set&lt;String&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ SetLikeVideo(videoId: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ addFallow(user: UserItem)</TD></TR>
<TR><TD ALIGN="LEFT" >+ addVideo(videoId: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ checkPassword(password: String): Boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ delDislike(videoId: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ delFollow(user: UserItem)</TD></TR>
<TR><TD ALIGN="LEFT" >+ delLike(videoId: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ delUploadedVideo(videoId: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ dislikeVideo(videoId: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getIsFollowed(user: UserItem): Boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ getIsFollowing(user: UserItem): Boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ hasDisliked(videoId: String): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ hasLiked(videoId: String): boolean</TD></TR>
<TR><TD ALIGN="LEFT" >+ likeVideo(videoId: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ removeDislike(videoId: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ removeLike(videoId: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

UserRepository301782323[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)UserRepository</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   executor: Executor [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   serverAPI: ServerAPInterface [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   userDao: UserDao [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getUser(userId: String): LiveData&lt;UserItem&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ insertUser(user: UserItem)</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateUser(user: UserItem)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

UserResponse1513582101[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)UserResponse</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   country: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   dislikedVideoIds: List&lt;String&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   email: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   followers: List&lt;String&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   following: List&lt;String&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   fullName: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   likedVideoIds: List&lt;String&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   phoneNumber: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   profilePhoto: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   userId: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   userName: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   videosIds: List&lt;String&gt; [0..*]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ toUserItem(): UserItem</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

UserViewModel415753121[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)UserViewModel</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   user: LiveData&lt;UserItem&gt; [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   userRepository: UserRepository [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getUser(userId: String): LiveData&lt;UserItem&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ insertUser(newUser: UserItem)</TD></TR>
<TR><TD ALIGN="LEFT" >+ updateUser(updatedUser: UserItem)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

VideoDao668488047[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(I)VideoDao</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getAllVideos(): LiveData&lt;List&lt;PreviewVideoCard&gt;&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getAllVideosSync(): List&lt;PreviewVideoCard&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getVideoById(videoId: String): LiveData&lt;PreviewVideoCard&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getVideoByIdSync(videoId: String): PreviewVideoCard</TD></TR>
<TR><TD ALIGN="LEFT" >+ getVideosByUserId(userId: String): LiveData&lt;List&lt;PreviewVideoCard&gt;&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getVideosByUserIdSync(userId: String): List&lt;PreviewVideoCard&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ insertVideo(video: PreviewVideoCard)</TD></TR>
<TR><TD ALIGN="LEFT" >+ insertVideos(videos: List&lt;PreviewVideoCard&gt;)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#F1E5FD"
];

VideoDao_Impl668488047[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)VideoDao_Impl</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   __commentItemTypeConverter: CommentItemTypeConverter [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   __db: RoomDatabase [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   __insertionAdapterOfPreviewVideoCard: EntityInsertionAdapter&lt;PreviewVideoCard&gt; [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   __stringListTypeConverter: StringListTypeConverter [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ getVideoById(videoId: String): LiveData&lt;PreviewVideoCard&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getVideoByIdSync(videoId: String): PreviewVideoCard</TD></TR>
<TR><TD ALIGN="LEFT" >+ getVideosByUserId(userId: String): LiveData&lt;List&lt;PreviewVideoCard&gt;&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getVideosByUserIdSync(userId: String): List&lt;PreviewVideoCard&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ insertVideo(video: PreviewVideoCard)</TD></TR>
<TR><TD ALIGN="LEFT" >+ insertVideos(videos: List&lt;PreviewVideoCard&gt;)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

VideoPlayerFragment751163288[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)VideoPlayerFragment</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   adapter: CommentSection_Adapter [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   buttonBar: ConstraintLayout [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   commentButton: Button [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   commentItemArrayList: ArrayList&lt;CommentItem&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   commentSectionContainer: ConstraintLayout [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   currentPosition: int [1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   description: TextView [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   descriptionButton: TextView [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   likeButton: ImageButton [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   likesTextView: TextView [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   mediaController: MediaController [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   profilePicture: ImageView [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   recyclerView: RecyclerView [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   shareButton: Button [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   titleTextView: TextView [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   unlikeButton: ImageButton [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   userNameTextView: TextView [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   userViewModel: UserViewModel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   video: PreviewVideoCard [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   videoId: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   videoView: VideoView [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   videoViewModel: VideoViewModel [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   views: TextView [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ hideMediaController()</TD></TR>
<TR><TD ALIGN="LEFT" >- incrementViewCount(videoId: String)</TD></TR>
<TR><TD ALIGN="LEFT" >- initializeCommentsSection(comments: ArrayList&lt;CommentItem&gt;)</TD></TR>
<TR><TD ALIGN="LEFT" >- initializeDescription()</TD></TR>
<TR><TD ALIGN="LEFT" >- initializeVideo(video: PreviewVideoCard)</TD></TR>
<TR><TD ALIGN="LEFT" >- initializeVideoDetails(video: PreviewVideoCard)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onCreateView(inflater: LayoutInflater, container: ViewGroup, savedInstanceState: Bundle): View</TD></TR>
<TR><TD ALIGN="LEFT" >+ onDeleteComment(position: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onEditComment(position: int)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onPause()</TD></TR>
<TR><TD ALIGN="LEFT" >+ onResume()</TD></TR>
<TR><TD ALIGN="LEFT" >+ onSaveInstanceState(outState: Bundle)</TD></TR>
<TR><TD ALIGN="LEFT" >+ onStop()</TD></TR>
<TR><TD ALIGN="LEFT" >- showShareMenu()</TD></TR>
<TR><TD ALIGN="LEFT" >- toggleDescriptionComments()</TD></TR>
<TR><TD ALIGN="LEFT" >- updateLikeDislikeButtons()</TD></TR>
<TR><TD ALIGN="LEFT" >- updateLikesAndViewsCount()</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

VideoRepository301782323[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)VideoRepository</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   executor: Executor [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   serverAPI: ServerAPInterface [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   videoDao: VideoDao [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ dislikeVideo(videoId: String, userId: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getVideo(videoId: String): LiveData&lt;PreviewVideoCard&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getVideosByUser(userId: String): LiveData&lt;List&lt;PreviewVideoCard&gt;&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ incrementVideoViews(videoId: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ insertComment(comment: CommentItem, videoId: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ insertVideo(video: PreviewVideoCard)</TD></TR>
<TR><TD ALIGN="LEFT" >+ likeVideo(videoId: String, userId: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

VideoViewModel415753121[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)VideoViewModel</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   allVideos: LiveData&lt;List&lt;PreviewVideoCard&gt;&gt; [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   video: LiveData&lt;PreviewVideoCard&gt; [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   videoRepository: VideoRepository [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ dislikeVideo(videoId: String, userId: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ getVideo(videoId: String): LiveData&lt;PreviewVideoCard&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getVideosByUser(userId: String): LiveData&lt;List&lt;PreviewVideoCard&gt;&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ incrementVideoViews(videoId: String)</TD></TR>
<TR><TD ALIGN="LEFT" >+ insertVideo(video: PreviewVideoCard)</TD></TR>
<TR><TD ALIGN="LEFT" >+ likeVideo(videoId: String, userId: String)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
CommentActionListener877673192 -> VideoPlayerFragment751163288[arrowhead=none, arrowtail=empty, dir=both];
CommentSection_Adapter1564424876 -> CommentActionListener877673192[label="commentActionListener
[0..1]"];
CommentSection_Adapter1564424876 -> CommentItem52669585[label="commentItemArrayList
[0..*]"];
CommentSection_Adapter1564424876 -> ServerAPI1808078836[label="onBindViewHolder() -> constructUrl()"];
CommentSection_Adapter1564424876 -> UserViewModel415753121[label="onBindViewHolder() -> getUser()"];
PreviewVideoCard52669585 -> CommentItem52669585[label="comments
[0..*]"];
ServerAPI1808078836 -> ServerAPInterface1808078836[label="serverAPInterface
[0..1]"];
UserDao668488047 -> UserDao_Impl668488047[arrowhead=none, arrowtail=empty, dir=both];
UserDao_Impl668488047 -> SetTypeConverter209323434[label="__setTypeConverter
[0..1]"];
UserDao_Impl668488047 -> UserItem52669585[label="__insertionAdapterOfUserItem
[0..1]"];
UserDao_Impl668488047 -> UserItem52669585[label="__updateAdapterOfUserItem
[0..1]"];
UserRepository301782323 -> ServerAPInterface1808078836[label="serverAPI
[0..1]"];
UserRepository301782323 -> UserDao668488047[label="userDao
[0..1]"];
UserRepository301782323 -> UserResponse1513582101[label="getUser() -> toUserItem()"];
UserViewModel415753121 -> UserItem52669585[label="user
[0..1]"];
UserViewModel415753121 -> UserRepository301782323[label="userRepository
[0..1]"];
VideoDao668488047 -> VideoDao_Impl668488047[arrowhead=none, arrowtail=empty, dir=both];
VideoDao_Impl668488047 -> CommentItemTypeConverter209323434[label="__commentItemTypeConverter
[0..1]"];
VideoDao_Impl668488047 -> PreviewVideoCard52669585[label="__insertionAdapterOfPreviewVideoCard
[0..1]"];
VideoDao_Impl668488047 -> StringListTypeConverter209323434[label="__stringListTypeConverter
[0..1]"];
VideoPlayerFragment751163288 -> CommentItem52669585[label="commentItemArrayList
[0..*]"];
VideoPlayerFragment751163288 -> CommentSection_Adapter1564424876[label="adapter
[0..1]"];
VideoPlayerFragment751163288 -> PreviewVideoCard52669585[label="video
[0..1]"];
VideoPlayerFragment751163288 -> UserViewModel415753121[label="userViewModel
[0..1]"];
VideoPlayerFragment751163288 -> VideoViewModel415753121[label="videoViewModel
[0..1]"];
VideoRepository301782323 -> ServerAPInterface1808078836[label="serverAPI
[0..1]"];
VideoRepository301782323 -> VideoDao668488047[label="videoDao
[0..1]"];
VideoViewModel415753121 -> PreviewVideoCard52669585[label="allVideos
[0..1]"];
VideoViewModel415753121 -> PreviewVideoCard52669585[label="video
[0..1]"];
VideoViewModel415753121 -> VideoRepository301782323[label="videoRepository
[0..1]"];
    
}
@enduml