@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "com.example.crispycrumbs.view.VideoPlayerFragment#onCreateView(LayoutInflater,ViewGroup,Bundle)",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "com.example.crispycrumbs.*",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "com.example.crispycrumbs.view.VideoPlayerFragment",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1322970774 { 
   	label=example
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1709816830 { 
   	label=crispycrumbs
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_113624790 { 
   	label=UserRepository
	labeljust=l
	fillcolor=white
	style=filled
   
   UserRepository301782323XXXgetUser1808118735[
	label="+ getUser()"
	style=filled
	fillcolor=white
	tooltip="UserRepository

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1272549126 { 
   	label=VideoPlayerFragment
	labeljust=l
	fillcolor=white
	style=filled
   
   VideoPlayerFragment751163288XXXonCreateView43515399[
	label="+ onCreateView()"
	style=filled
	fillcolor=white
	tooltip="VideoPlayerFragment

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_136598025 { 
   	label=VideoDao_Impl
	labeljust=l
	fillcolor=white
	style=filled
   
   VideoDao_Impl668488047XXXgetVideoByIdSync1808118735[
	label="+ getVideoByIdSync()"
	style=filled
	fillcolor=white
	tooltip="VideoDao_Impl

null"
	fontcolor=darkgreen
];

VideoDao_Impl668488047XXXinsertVideo917991581[
	label="+ insertVideo()"
	style=filled
	fillcolor=white
	tooltip="VideoDao_Impl

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_148911332 { 
   	label=VideoRepository
	labeljust=l
	fillcolor=white
	style=filled
   
   VideoRepository301782323XXXdislikeVideo2013066710[
	label="+ dislikeVideo()"
	style=filled
	fillcolor=white
	tooltip="VideoRepository

null"
	fontcolor=darkgreen
];

VideoRepository301782323XXXgetVideo1808118735[
	label="+ getVideo()"
	style=filled
	fillcolor=white
	tooltip="VideoRepository

null"
	fontcolor=darkgreen
];

VideoRepository301782323XXXincrementVideoViews1808118735[
	label="+ incrementVideoViews()"
	style=filled
	fillcolor=white
	tooltip="VideoRepository

null"
	fontcolor=darkgreen
];

VideoRepository301782323XXXlikeVideo2013066710[
	label="+ likeVideo()"
	style=filled
	fillcolor=white
	tooltip="VideoRepository

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1635526580 { 
   	label=UserViewModel
	labeljust=l
	fillcolor=white
	style=filled
   
   UserViewModel415753121XXXgetUser1808118735[
	label="+ getUser()"
	style=filled
	fillcolor=white
	tooltip="UserViewModel

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1739912081 { 
   	label=UserResponse
	labeljust=l
	fillcolor=white
	style=filled
   
   UserResponse1513582101XXXtoUserItem0[
	label="+ toUserItem()"
	style=filled
	fillcolor=white
	tooltip="UserResponse

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1935145481 { 
   	label=UserDao_Impl
	labeljust=l
	fillcolor=white
	style=filled
   
   UserDao_Impl668488047XXXgetUserByIdSync1808118735[
	label="+ getUserByIdSync()"
	style=filled
	fillcolor=white
	tooltip="UserDao_Impl

null"
	fontcolor=darkgreen
];

UserDao_Impl668488047XXXinsertUser202153570[
	label="+ insertUser()"
	style=filled
	fillcolor=white
	tooltip="UserDao_Impl

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_571882075 { 
   	label=UserItem
	labeljust=l
	fillcolor=white
	style=filled
   
   UserItem52669585XXXdislikeVideo1808118735[
	label="+ dislikeVideo()"
	style=filled
	fillcolor=white
	tooltip="UserItem

null"
	fontcolor=darkgreen
];

UserItem52669585XXXhasDisliked1808118735[
	label="+ hasDisliked()"
	style=filled
	fillcolor=white
	tooltip="UserItem

null"
	fontcolor=darkgreen
];

UserItem52669585XXXhasLiked1808118735[
	label="+ hasLiked()"
	style=filled
	fillcolor=white
	tooltip="UserItem

null"
	fontcolor=darkgreen
];

UserItem52669585XXXlikeVideo1808118735[
	label="+ likeVideo()"
	style=filled
	fillcolor=white
	tooltip="UserItem

null"
	fontcolor=darkgreen
];

UserItem52669585XXXremoveDislike1808118735[
	label="+ removeDislike()"
	style=filled
	fillcolor=white
	tooltip="UserItem

null"
	fontcolor=darkgreen
];

UserItem52669585XXXremoveLike1808118735[
	label="+ removeLike()"
	style=filled
	fillcolor=white
	tooltip="UserItem

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_7212605 { 
   	label=ServerAPI
	labeljust=l
	fillcolor=white
	style=filled
   
   ServerAPI1808078836XXXconstructUrl1808118735[
	label="+ constructUrl()"
	style=filled
	fillcolor=white
	tooltip="ServerAPI

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_849723222 { 
   	label=VideoViewModel
	labeljust=l
	fillcolor=white
	style=filled
   
   VideoViewModel415753121XXXdislikeVideo2013066710[
	label="+ dislikeVideo()"
	style=filled
	fillcolor=white
	tooltip="VideoViewModel

null"
	fontcolor=darkgreen
];

VideoViewModel415753121XXXgetVideo1808118735[
	label="+ getVideo()"
	style=filled
	fillcolor=white
	tooltip="VideoViewModel

null"
	fontcolor=darkgreen
];

VideoViewModel415753121XXXincrementVideoViews1808118735[
	label="+ incrementVideoViews()"
	style=filled
	fillcolor=white
	tooltip="VideoViewModel

null"
	fontcolor=darkgreen
];

VideoViewModel415753121XXXlikeVideo2013066710[
	label="+ likeVideo()"
	style=filled
	fillcolor=white
	tooltip="VideoViewModel

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
UserRepository301782323XXXgetUser1808118735 -> UserDao_Impl668488047XXXgetUserByIdSync1808118735;
UserRepository301782323XXXgetUser1808118735 -> UserDao_Impl668488047XXXinsertUser202153570;
UserRepository301782323XXXgetUser1808118735 -> UserResponse1513582101XXXtoUserItem0;
UserViewModel415753121XXXgetUser1808118735 -> UserRepository301782323XXXgetUser1808118735;
VideoPlayerFragment751163288XXXonCreateView43515399 -> ServerAPI1808078836XXXconstructUrl1808118735;
VideoPlayerFragment751163288XXXonCreateView43515399 -> UserItem52669585XXXdislikeVideo1808118735;
VideoPlayerFragment751163288XXXonCreateView43515399 -> UserItem52669585XXXhasDisliked1808118735;
VideoPlayerFragment751163288XXXonCreateView43515399 -> UserItem52669585XXXhasLiked1808118735;
VideoPlayerFragment751163288XXXonCreateView43515399 -> UserItem52669585XXXlikeVideo1808118735;
VideoPlayerFragment751163288XXXonCreateView43515399 -> UserItem52669585XXXremoveDislike1808118735;
VideoPlayerFragment751163288XXXonCreateView43515399 -> UserItem52669585XXXremoveLike1808118735;
VideoPlayerFragment751163288XXXonCreateView43515399 -> UserViewModel415753121XXXgetUser1808118735;
VideoPlayerFragment751163288XXXonCreateView43515399 -> VideoViewModel415753121XXXdislikeVideo2013066710;
VideoPlayerFragment751163288XXXonCreateView43515399 -> VideoViewModel415753121XXXgetVideo1808118735;
VideoPlayerFragment751163288XXXonCreateView43515399 -> VideoViewModel415753121XXXincrementVideoViews1808118735;
VideoPlayerFragment751163288XXXonCreateView43515399 -> VideoViewModel415753121XXXlikeVideo2013066710;
VideoRepository301782323XXXdislikeVideo2013066710 -> UserItem52669585XXXdislikeVideo1808118735;
VideoRepository301782323XXXdislikeVideo2013066710 -> UserItem52669585XXXhasDisliked1808118735;
VideoRepository301782323XXXdislikeVideo2013066710 -> UserItem52669585XXXhasLiked1808118735;
VideoRepository301782323XXXdislikeVideo2013066710 -> UserItem52669585XXXremoveDislike1808118735;
VideoRepository301782323XXXdislikeVideo2013066710 -> UserItem52669585XXXremoveLike1808118735;
VideoRepository301782323XXXdislikeVideo2013066710 -> VideoRepository301782323XXXgetVideo1808118735;
VideoRepository301782323XXXincrementVideoViews1808118735 -> VideoDao_Impl668488047XXXgetVideoByIdSync1808118735;
VideoRepository301782323XXXincrementVideoViews1808118735 -> VideoRepository301782323XXXgetVideo1808118735;
VideoRepository301782323XXXlikeVideo2013066710 -> UserItem52669585XXXhasDisliked1808118735;
VideoRepository301782323XXXlikeVideo2013066710 -> UserItem52669585XXXhasLiked1808118735;
VideoRepository301782323XXXlikeVideo2013066710 -> UserItem52669585XXXlikeVideo1808118735;
VideoRepository301782323XXXlikeVideo2013066710 -> UserItem52669585XXXremoveDislike1808118735;
VideoRepository301782323XXXlikeVideo2013066710 -> UserItem52669585XXXremoveLike1808118735;
VideoRepository301782323XXXlikeVideo2013066710 -> VideoDao_Impl668488047XXXinsertVideo917991581;
VideoRepository301782323XXXlikeVideo2013066710 -> VideoRepository301782323XXXgetVideo1808118735;
VideoViewModel415753121XXXdislikeVideo2013066710 -> VideoRepository301782323XXXdislikeVideo2013066710;
VideoViewModel415753121XXXgetVideo1808118735 -> VideoRepository301782323XXXgetVideo1808118735;
VideoViewModel415753121XXXincrementVideoViews1808118735 -> VideoRepository301782323XXXincrementVideoViews1808118735;
VideoViewModel415753121XXXlikeVideo2013066710 -> VideoRepository301782323XXXlikeVideo2013066710;
    
}
@enduml